apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - postgres.yaml
  - elasticsearch.yaml
  - fluentbit.yaml
  - ingress.yaml

namespace: wishlist 